var _templateObject, _templateObject2, _templateObject3, _templateObject4, _templateObject5, _templateObject6, _templateObject7, _templateObject8, _templateObject9, _templateObject0, _templateObject1, _templateObject10, _templateObject11, _templateObject12, _templateObject13, _templateObject14;
function _taggedTemplateLiteralLoose(e, t) { return t || (t = e.slice(0)), e.raw = t, e; }
import styled, { keyframes } from 'styled-components';
export var StyledTerminalWrapper = styled.div(_templateObject || (_templateObject = _taggedTemplateLiteralLoose(["\n  position: fixed;\n  top: 0;\n  left: 0;\n  right: 0;\n  bottom: 0;\n  font-size: 14px;\n  width: 100%;\n  max-width: 100%;\n  margin: 0 !important;\n  border-radius: 0;\n  color: white;\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n  box-shadow: none;\n  z-index: 9999;\n\n  @media screen and (max-width: 760px) {\n    width: 100%;\n    margin-top: 0 !important;\n  }\n"])));
export var StyledTerminal = styled.div(_templateObject2 || (_templateObject2 = _taggedTemplateLiteralLoose(["\n  position: absolute;\n  top: 0;\n  left: 0;\n  right: 0;\n  bottom: 0;\n  overflow: auto;\n  z-index: 1;\n  margin-top: 30px;\n  height: calc(100vh - 30px);\n  max-height: calc(100vh - 30px);\n  background-color: rgba(0, 0, 0, 0.95);\n  backdrop-filter: blur(20px);\n  -webkit-backdrop-filter: blur(20px);\n  border-radius: 0;\n\n  @media screen and (max-width: 760px) {\n    box-shadow: none;\n    height: calc(100vh - 30px);\n    max-height: calc(100vh - 30px);\n  }\n\n  &::-webkit-scrollbar {\n    width: 8px;\n  }\n\n  &::-webkit-scrollbar-track {\n    background: rgba(0, 0, 0, 0.1);\n  }\n\n  &::-webkit-scrollbar-thumb {\n    background: rgba(255, 255, 255, 0.2);\n    border-radius: 4px;\n  }\n"])));
export var StyledTerminalInner = styled.div(_templateObject3 || (_templateObject3 = _taggedTemplateLiteralLoose(["\n  padding: 20px;\n  font-weight: normal;\n  font-family: \"SF Mono\", \"Fira Code\", \"Source Code Pro\", Monaco, Menlo,\n    Consolas, monospace;\n  color: #fff;\n  line-height: 1.5;\n\n  @media screen and (max-width: 760px) {\n    padding: 20px 10px;\n  }\n"])));
export var StyledInputWrapper = styled.p(_templateObject4 || (_templateObject4 = _taggedTemplateLiteralLoose(["\n  display: flex;\n  align-items: center;\n  margin: 0;\n  padding: 8px 0;\n  word-spacing: 0;\n  letter-spacing: 0;\n  word-break: break-all;\n  font-weight: 400;\n  font-family: \"SF Mono\", Fira Code, Source Code Pro, Monaco, Menlo, Consolas,\n    monospace;\n  color: #fff;\n"])));
export var StyledInput = styled.input(_templateObject5 || (_templateObject5 = _taggedTemplateLiteralLoose(["\n  position: absolute;\n  background: transparent;\n  border: none;\n  width: 1px;\n  height: 1px;\n  opacity: 0;\n  padding: 0;\n  margin: 0;\n  cursor: default;\n  pointer-events: none;\n  z-index: -1;\n\n  &:focus {\n    outline: none;\n    border: none;\n  }\n"])));
export var StyledPrompt = styled.span(_templateObject6 || (_templateObject6 = _taggedTemplateLiteralLoose(["\n  word-break: break-all;\n  color: #56b6c2;\n  margin-right: 8px;\n"])));
var loadingDots = keyframes(_templateObject7 || (_templateObject7 = _taggedTemplateLiteralLoose(["\n  0%, 20% {\n    color: rgba(255, 255, 255, 0);\n    text-shadow: 0.25em 0 0 rgba(255, 255, 255, 0), 0.5em 0 0 rgba(255, 255, 255, 0);\n  }\n  40% {\n    color: white;\n    text-shadow: 0.25em 0 0 rgba(255, 255, 255, 0), 0.5em 0 0 rgba(255, 255, 255, 0);\n  }\n  60% {\n    text-shadow: 0.25em 0 0 white, 0.5em 0 0 rgba(255, 255, 255, 0);\n  }\n  80%, 100% {\n    text-shadow: 0.25em 0 0 white, 0.5em 0 0 white;\n  }\n"])));
export var StyledLoadingCursor = styled.span(_templateObject8 || (_templateObject8 = _taggedTemplateLiteralLoose(["\n  font: 300 1.5em \"SF Mono\";\n  animation: ", " 1s steps(5, end) infinite;\n"])), loadingDots);
var blinkDot = keyframes(_templateObject9 || (_templateObject9 = _taggedTemplateLiteralLoose(["\n  0%, 100% {\n    opacity: 1;\n  }\n  50% {\n    opacity: 0;\n  }\n"])));
export var StyledBlinkCursor = styled.span(_templateObject0 || (_templateObject0 = _taggedTemplateLiteralLoose(["\n  position: relative;\n  display: inline-flex;\n  align-items: center;\n  width: 8px;\n  height: 17px;\n  line-height: 17px;\n  vertical-align: middle;\n  color: inherit;\n  margin-left: 0;\n  z-index: 1;\n\n  &::before {\n    content: '';\n    position: absolute;\n    top: 0;\n    left: 0;\n    width: 100%;\n    height: 100%;\n    background-color: ", ";\n    animation: ", " 1s step-end infinite;\n  }\n\n  ", "\n"])), function (props) {
  return props.children === "\xA0" ? '#56b6c2' : 'rgba(86, 182, 194, 0.7)';
}, blinkDot, function (props) {
  return props.children !== "\xA0" && "\n    &::after {\n      content: '';\n      position: absolute;\n      left: 0;\n      z-index: 2;\n      color: #abb2bf;\n    }\n  ";
});
export var StyledLine = styled.div(_templateObject1 || (_templateObject1 = _taggedTemplateLiteralLoose(["\n  word-break: break-all;\n  margin: 8px 0;\n  line-height: 1.5;\n\n  .cmd {\n    color: #abb2bf;\n  }\n\n  .info {\n    color: #61afef;\n  }\n\n  .warning {\n    color: #e5c07b;\n  }\n\n  .success {\n    color: #98c379;\n  }\n\n  .error {\n    color: #e06c75;\n  }\n\n  .system {\n    color: #c678dd;\n  }\n\n  .time {\n    color: #56b6c2;\n  }\n\n  .black {\n    color: #4b5263;\n  }\n\n  .time,\n  .system,\n  .error,\n  .success,\n  .warning,\n  .info,\n  .black {\n    margin-right: 8px;\n    padding: 2px 4px;\n    border-radius: 3px;\n    background: rgba(255, 255, 255, 0.1);\n  }\n"])));
export var StyledHeader = styled.div(_templateObject10 || (_templateObject10 = _taggedTemplateLiteralLoose(["\n  position: absolute;\n  z-index: 2;\n  top: 0;\n  right: 0;\n  left: 0;\n  height: 30px;\n  background: rgba(30, 30, 30, 0.95);\n  backdrop-filter: blur(20px);\n  -webkit-backdrop-filter: blur(20px);\n  border-radius: 0;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  border-bottom: 1px solid rgba(255, 255, 255, 0.1);\n  -webkit-app-region: drag;\n"])));
export var StyledHeaderTitle = styled.h4(_templateObject11 || (_templateObject11 = _taggedTemplateLiteralLoose(["\n  margin: 0;\n  font-size: 13px;\n  letter-spacing: 0.5px;\n  font-weight: 400;\n  color: rgba(255, 255, 255, 0.8);\n  font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica,\n    Arial, sans-serif;\n"])));
export var StyledHeaderDotList = styled.ul(_templateObject12 || (_templateObject12 = _taggedTemplateLiteralLoose(["\n  position: absolute;\n  top: 50%;\n  transform: translateY(-50%);\n  left: 10px;\n  padding: 0;\n  margin: 0;\n  display: flex;\n  gap: 6px;\n  list-style: none;\n"])));
export var StyledHeaderDotItem = styled.li(_templateObject13 || (_templateObject13 = _taggedTemplateLiteralLoose(["\n  width: 12px;\n  height: 12px;\n  border-radius: 50%;\n  background-color: ", ";\n  transition: all 0.2s ease;\n  cursor: pointer;\n\n  &:hover {\n    filter: brightness(0.8);\n  }\n"])), function (props) {
  switch (props.color) {
    case 'red':
      return '#ff5f56';
    case 'yellow':
      return '#ffbd2e';
    case 'green':
      return '#27c93f';
    default:
      return '#ddd';
  }
});
export var StyledCommand = styled.span(_templateObject14 || (_templateObject14 = _taggedTemplateLiteralLoose(["\n  font-size: inherit;\n  color: inherit;\n  font-family: inherit;\n  line-height: inherit;\n  vertical-align: middle;\n"])));